FROM oven/bun:1-alpine 

WORKDIR /user/src/app

ARG DATABASE_URL

COPY ../packages ./packages
COPY ../bun.lock .

COPY ../package.json .
COPY ../turbo.json .

COPY ../apps/web ./apps/web

RUN bun install 
RUN bun turbo run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build 

EXPOSE 3000

CMD [ "bun","run","start:web" ]
