FROM oven/bun:1 

WORKDIR /user/src/app

COPY ../packages ./packages
COPY ../bun.lock .

COPY ../package.json .
COPY ../turbo.json .

COPY ../apps/web/package.json ./apps/web/package.json

RUN bun install 

COPY ../apps/web ./apps/web

RUN bun turbo run db:generate
RUN bun run build 

EXPOSE 3000

CMD [ "bun","run","start:web" ]
