FROM oven/bun:1 

WORKDIR /user/src/app

COPY ../bun.lock .
COPY ../package.json .
COPY ../turbo.json .

COPY ../packages ./packages
COPY ../apps/http-backend/package.json ./apps/http-backend/package.json

RUN bun install 

COPY ../apps/http-backend ./apps/http-backend

RUN bun turbo run db:generate

EXPOSE 3001

CMD [ "bun","run","start:backend" ]
